name: Build

on:
    workflow_call:
        inputs: {}
    workflow_dispatch:
        inputs: {}

jobs:
    package-cimbar:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
              with:
                  submodules: "recursive"

            - name: Get openCV
              run: |
                  wget https://github.com/opencv/opencv/archive/refs/tags/4.10.0.zip
                  unzip 4.10.0.zip
                  mv opencv-4.10.0 opencv4

            - name: Run the build process with Docker
              uses: addnab/docker-run-action@v3
              with:
                  image: emscripten/emsdk:3.1.69
                  options: -v ${{ github.workspace }}:/usr/src/app
                  shell: bash
                  run: |
                      bash /usr/src/app/package-wasm.sh

            - name: Show results
              run: ls -l web/

            - name: Create release
              uses: softprops/action-gh-release@v1
              with:
                  draft: true
                  files: |
                      web/cimbar.asmjs.zip
                      web/cimbar.wasm.tar.gz
                      web/cimbar_js.html

            - name: Upload artifact
              uses: actions/upload-artifact@v4.5.0
              with:
                  name: web.zip
                  path: web/
